print("Twinkle, twinkle, little star,")
print("\t How I wonder what you are! ")
print("\t\t Up above the world so high, ")
print("\t\t Like a diamond in the sky.")
print("Twinkle, twinkle, little star,")
print("\t How I wonder what you are")